#!/usr/bin/perl

# this script makes the nodes.csv lookup file on a Cray XT/XE system via:
#   xtprocadmin -A | ./xtprocadmin2nodes > nodes.csv

# if you successfully do the below, we'll also use that info
#   echo "use XTAdmin; select * from processor;" | mysql > XTAdmin.processor
$xtadmin = "XTAdmin.processor";
if (-s $xtadmin) {
	open XTADMIN, $xtadmin or die "Can't read $xtadmin: $!\n";
	$header = <XTADMIN>;
	($nid, @cols) = split /\s+/, $header;
	splice @cols, 6,1; # omit processor_status
	@{$xtadmin{"header"}} = @cols;
	while (<XTADMIN>) {
		($nid, @cols) = split /\s+/, $_;
		splice @cols, 6, 1; # omit processor_status
		@{$xtadmin{$nid}} = @cols;
	}
	close XTADMIN;
}


while (<>) {
	chomp;
	tr/\(\)//d; # delete parens
	$_ = lc $_; # lower case
	@F = split; # split on whitespace
	if (/nid/) { # first line is header
		$F[2] = "node";
		delete @F[10,11,12,13]; # unwanted
		print join ",", @F, @{$xtadmin{"header"}};
	}
	else {
		print join ",", @F, @{$xtadmin{$F[0]}};
	}
	print "\n";
}
